version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - app-data:/apps/banana-app
      - letsencrypt:/etc/letsencrypt/live
    depends_on:
      - app
    environment:
      - TZ=Asia/Tokyo
      - LETSENCRYPT_HOSTS
      - LETSENCRYPT_MAIL
      - LETSENCRYPT_SUBJECT
  app:
    build:
      context: .
      dockerfile: ./rails/Dockerfile
    #command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma_production.rb
    volumes:
      - app-data:/apps/banana-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - RAILS_LOG_TO_STDOUT=ON
      - SECRET_KEY_BASE
      - DB_HOST=db
      - RAILS_ENV
      - MYSQL_USER
      - MYSQL_PASSWORD
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ=Asia/Tokyo
volumes:
  app-data:
  db-data:
  letsencrypt: